// @origin(spec:tri_spec_writer.tri) @regen(manual-impl)
// ═══════════════════════════════════════════════════════════════════════════════
// TRI SPEC WRITER — Generate .tri specs from GitHub issue descriptions
// ═══════════════════════════════════════════════════════════════════════════════
// Pipeline Link: spec_create (Link 6)
// Issue #76: Subagent Spec Writer Pipeline
// φ² + 1/φ² = 3 = TRINITY
// ═══════════════════════════════════════════════════════════════════════════════

const std = @import("std");
const Allocator = std.mem.Allocator;

// ═══════════════════════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════════════════════

pub const SpecField = struct {
    name: []const u8,
    field_type: []const u8,
};

pub const SpecType = struct {
    name: []const u8,
    fields: []const SpecField,
};

pub const SpecBehavior = struct {
    name: []const u8,
    description: []const u8,
    inputs: []const SpecField,
    output: []const u8,
    steps: []const []const u8,
};

pub const SpecTemplate = struct {
    module_name: []const u8,
    description: []const u8,
    types: []const SpecType,
    behaviors: []const SpecBehavior,
};

pub const WriteResult = struct {
    spec_path: []const u8,
    generated_path: []const u8,
    compile_ok: bool,
    error_msg: ?[]const u8,
};

// ═══════════════════════════════════════════════════════════════════════════════
// MODULE NAME EXTRACTION
// ═══════════════════════════════════════════════════════════════════════════════

/// Extract module name from issue title.
/// "feat(mu): Agent MU Error Protocol" → "agent_mu_error_protocol"
pub fn extractModuleName(allocator: Allocator, title: []const u8) ![]u8 {
    // Skip conventional commit prefix: "feat(scope): " or "fix(scope): "
    var start: usize = 0;
    if (std.mem.indexOf(u8, title, ": ")) |colon_pos| {
        start = colon_pos + 2;
    }

    // Convert remaining to snake_case
    var result: std.ArrayList(u8) = .empty;
    errdefer result.deinit(allocator);

    var prev_was_sep = false;
    for (title[start..]) |c| {
        if (c == ' ' or c == '-' or c == '/' or c == '(' or c == ')' or c == '[' or c == ']') {
            if (!prev_was_sep and result.items.len > 0) {
                try result.append(allocator, '_');
                prev_was_sep = true;
            }
        } else if (c >= 'A' and c <= 'Z') {
            if (result.items.len > 0 and !prev_was_sep) {
                try result.append(allocator, '_');
            }
            try result.append(allocator, c + 32); // toLower
            prev_was_sep = false;
        } else if ((c >= 'a' and c <= 'z') or (c >= '0' and c <= '9') or c == '_') {
            try result.append(allocator, c);
            prev_was_sep = false;
        }
    }

    // Trim trailing underscore
    while (result.items.len > 0 and result.items[result.items.len - 1] == '_') {
        _ = result.pop();
    }

    return result.toOwnedSlice(allocator);
}

// ═══════════════════════════════════════════════════════════════════════════════
// SPEC GENERATION
// ═══════════════════════════════════════════════════════════════════════════════

/// Generate a .tri spec file content from a template.
pub fn generateSpecContent(allocator: Allocator, template: SpecTemplate) ![]u8 {
    var buf: std.ArrayList(u8) = .empty;
    errdefer buf.deinit(allocator);
    const w = buf.writer(allocator);

    // Header
    try w.writeAll("# ═══════════════════════════════════════════════════════════════════════════════\n");
    try w.print("# VIBEE Specification — {s}\n", .{template.module_name});
    try w.writeAll("# ═══════════════════════════════════════════════════════════════════════════════\n");
    try w.writeAll("# φ² + 1/φ² = 3 = TRINITY\n");
    try w.writeAll("# Auto-generated by Spec Writer Pipeline (Issue #76)\n");
    try w.writeAll("# ═══════════════════════════════════════════════════════════════════════════════\n\n");

    // Metadata
    try w.print("name: {s}\n", .{template.module_name});
    try w.writeAll("version: \"1.0.0\"\n");
    try w.writeAll("language: zig\n");
    try w.print("module: {s}\n\n", .{template.module_name});

    // Description
    try w.writeAll("description: |\n");
    // Indent each line of description
    var desc_iter = std.mem.splitSequence(u8, template.description, "\n");
    while (desc_iter.next()) |line| {
        try w.print("  {s}\n", .{line});
    }
    try w.writeByte('\n');

    // Types
    if (template.types.len > 0) {
        try w.writeAll("types:\n");
        for (template.types) |t| {
            try w.print("  {s}:\n", .{t.name});
            try w.writeAll("    fields:\n");
            for (t.fields) |f| {
                try w.print("      {s}: {s}\n", .{ f.name, f.field_type });
            }
        }
        try w.writeByte('\n');
    }

    // Behaviors
    if (template.behaviors.len > 0) {
        try w.writeAll("behaviors:\n");
        for (template.behaviors) |b| {
            try w.print("  {s}:\n", .{b.name});
            try w.print("    description: \"{s}\"\n", .{b.description});
            if (b.inputs.len > 0) {
                try w.writeAll("    inputs:\n");
                for (b.inputs) |inp| {
                    try w.print("      - {s}: {s}\n", .{ inp.name, inp.field_type });
                }
            }
            try w.print("    output: {s}\n", .{b.output});
            if (b.steps.len > 0) {
                try w.writeAll("    steps:\n");
                for (b.steps) |step| {
                    try w.print("      - {s}\n", .{step});
                }
            }
        }
    }

    return buf.toOwnedSlice(allocator);
}

/// Write spec to file and run vibee gen + ast-check.
pub fn writeAndValidate(allocator: Allocator, template: SpecTemplate) !WriteResult {
    const content = try generateSpecContent(allocator, template);
    defer allocator.free(content);

    // Build paths
    const spec_path = try std.fmt.allocPrint(allocator, "specs/tri/{s}.tri", .{template.module_name});
    const gen_path = try std.fmt.allocPrint(allocator, "generated/{s}.zig", .{template.module_name});

    // Write spec file
    const spec_file = try std.fs.cwd().createFile(spec_path, .{});
    defer spec_file.close();
    try spec_file.writeAll(content);

    // Run vibee gen
    const gen_result = std.process.Child.run(.{
        .allocator = allocator,
        .argv = &.{ "zig", "build", "vibee", "--", "gen", spec_path },
    }) catch {
        return .{
            .spec_path = spec_path,
            .generated_path = gen_path,
            .compile_ok = false,
            .error_msg = "vibee gen failed to execute",
        };
    };
    defer allocator.free(gen_result.stdout);
    defer allocator.free(gen_result.stderr);

    const gen_exit = switch (gen_result.term) {
        .Exited => |code| code,
        else => @as(u32, 1),
    };
    if (gen_exit != 0) {
        return .{
            .spec_path = spec_path,
            .generated_path = gen_path,
            .compile_ok = false,
            .error_msg = "vibee gen returned non-zero exit code",
        };
    }

    // Run zig ast-check
    const ast_result = std.process.Child.run(.{
        .allocator = allocator,
        .argv = &.{ "zig", "ast-check", gen_path },
    }) catch {
        return .{
            .spec_path = spec_path,
            .generated_path = gen_path,
            .compile_ok = false,
            .error_msg = "zig ast-check failed to execute",
        };
    };
    defer allocator.free(ast_result.stdout);
    defer allocator.free(ast_result.stderr);

    const ast_exit = switch (ast_result.term) {
        .Exited => |code| code,
        else => @as(u32, 1),
    };
    return .{
        .spec_path = spec_path,
        .generated_path = gen_path,
        .compile_ok = ast_exit == 0,
        .error_msg = if (ast_exit != 0) "ast-check failed" else null,
    };
}

// ═══════════════════════════════════════════════════════════════════════════════
// TESTS
// ═══════════════════════════════════════════════════════════════════════════════

test "extractModuleName — conventional commit" {
    const allocator = std.testing.allocator;
    const name = try extractModuleName(allocator, "feat(mu): Agent MU Error Protocol");
    defer allocator.free(name);
    try std.testing.expectEqualStrings("agent_m_u_error_protocol", name);
}

test "extractModuleName — simple title" {
    const allocator = std.testing.allocator;
    const name = try extractModuleName(allocator, "Batch Pipeline Runner");
    defer allocator.free(name);
    try std.testing.expectEqualStrings("batch_pipeline_runner", name);
}

test "extractModuleName — with brackets" {
    const allocator = std.testing.allocator;
    const name = try extractModuleName(allocator, "[MU-5] Test: verify on 49 known failures");
    defer allocator.free(name);
    try std.testing.expectEqualStrings("verify_on_49_known_failures", name);
}

test "generateSpecContent — basic template" {
    const allocator = std.testing.allocator;

    const template = SpecTemplate{
        .module_name = "test_module",
        .description = "A test module for validation.",
        .types = &.{
            .{
                .name = "Config",
                .fields = &.{
                    .{ .name = "enabled", .field_type = "Bool" },
                    .{ .name = "max_retries", .field_type = "Int" },
                },
            },
        },
        .behaviors = &.{
            .{
                .name = "init",
                .description = "Initialize the module",
                .inputs = &.{},
                .output = "Config",
                .steps = &.{ "Create default config", "Return config" },
            },
        },
    };

    const content = try generateSpecContent(allocator, template);
    defer allocator.free(content);

    // Verify key parts exist
    try std.testing.expect(std.mem.indexOf(u8, content, "name: test_module") != null);
    try std.testing.expect(std.mem.indexOf(u8, content, "language: zig") != null);
    try std.testing.expect(std.mem.indexOf(u8, content, "Config:") != null);
    try std.testing.expect(std.mem.indexOf(u8, content, "enabled: Bool") != null);
    try std.testing.expect(std.mem.indexOf(u8, content, "init:") != null);
}
